# Site Settings
title: My Resume
url: 'https://minuscorp.github.io/'
baseurl: '/online-cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Jorge Revuelta Herrero
tagline: Senior iOS Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Born and grown in Salamanca, Spain. Obtained a Computer Science degree in 2015 and MSc in Artificial Intelligence in 2016 at the University of Salamanca (Spain). In 2017, he received the research internship by the Junta de Castilla y León and started pursuing a PhD at the BISITE Research Group.
His research interest focuses in the field of social networks, Big Data, Cloud Computing and data visualization. He also is Senior iOS Developer at Ebikemotion SL, that combines with OSS contribution in the iOS community in projects such as fastlane, RxSwift, Moya, ReactiveSwift and others.'

#sidebar links
email: jrevuelta@usal.es
phone: +34 675 35 81 22
website: blog.webjeda.com #do not add http://
linkedin: jorgerevueltaherrero
github: minuscorp
twitter: '@minuscorp'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
